name: Config validator
on:
  pull_request:
    branches:
      - main
    paths: # again, real path obfuscated 
      - 'deployments/../**' # <- One of my teammates suggested scoping this workflow only to changes in those files instead of running it everywhere. 

jobs:
  config_validator:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch repo
        uses: actions/checkout@v4

      - name: Set up Python 3.9
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Update package list
        run: |
          sudo apt update

      - name: Set up dependencies
        run: |
          pip install --upgrade pip
          pip install pyyaml

      - name: Validate YAML configurations
        run: python scripts/test_configmap.py